config/routes.rb
Kibble::Application.routes.draw do

    match "/" => redirect("/items")
    
    resources :items
    resources :stores
    resources :tags
    resources :categories
    resources :rules
    resources :professions

    post 'items/update_tags' => "items#update_tags" 
    get 'items/clone/:id' => "items#clone" 
    get 'stores/clone/:id' => "stores#clone" 
    get 'professions/clone/:id' => "professions#clone" 
    get 'export' => "export#index"
    get 'validate' => "items#validate"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/category.rb
class Category < ActiveRecord::Base
    attr_accessible :name, :prefix, :available_for, :required, :exclusive, :calculated_enc
    
    has_many :tags
end

app/models/store.rb
class Store < ActiveRecord::Base
    attr_accessible :name, :policy, :owner_profession, :owner_trait
    attr_accessible :bag_query, :bag_total_value, :bag_min_value 
    attr_accessible :bag_max_value, :tag_ids, :id, :created_at, :updated_at
    has_and_belongs_to_many :tags
    
    validates :name, :owner_profession, :presence => true
    validates :bag_total_value, :numericality => { :greater_than_or_equal_to => 10, :allow_blank => true }
    validates :bag_min_value, :numericality => { :greater_than_or_equal_to => 1, :allow_blank => true }
    validates :bag_max_value, :numericality => { :greater_than_or_equal_to => 1, :allow_blank => true }
    
    def pruned_tags
        frequency = (Tag.where(:cat => 'frequency').pluck(:name) & tags.pluck(:name))
        removals = Tag.where(:cat => ['kit']).pluck(:name)
        frequency + ((tags.pluck(:name).sort) - removals)
    end
    
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    
    # Item.includes(:tags).where(:tags => {:name => 'firearm'})
    def index
        @stores = Store.order(:name).find(:all)
        #@stores = Kaminari.paginate_array(@stores).page(params[:page]).per(30)
    end

    def show
        @store = Store.find(params[:id])
        @tags = Tag.store_tags
    end

    def new
        @store = Store.new
        @tags = Tag.store_tags
    end
    
    def clone
        @clone = Store.find(params[:id])
        @store = Store.new(@clone.attributes)
        @clone.tags.each do |tag|
            @store.tags << tag
        end
        @tags = Tag.store_tags
        render "new"
    end

    def edit
        @store = Store.find(params[:id])
        @tags = Tag.store_tags
    end

    def create
        @store = Store.new(params[:store])
        if @store.save
            redirect_to stores_path, :notice => 'Store was successfully created.'
        else
            @tags = Tag.store_tags
            render :action => "new"
        end
    end

    def update
        @store = Store.find(params[:id])

        if @store.update_attributes(params[:store])
            @stores = Store.all
            redirect_to stores_path, :notice => 'Store was successfully updated.'
        else
            @tags = Tag.store_tags
            render :action => "edit"
        end
    end

    def destroy
        @store = Store.find(params[:id])
        @store.destroy

        redirect_to stores_url
    end
    
end

app/views/stores/_form.html.erb
<%= render :partial => "shared/errors", :locals => { :model => @store } %>
<%= form_for(@store, :html => {:class => 'form-horizontal' }) do |f| %>
    <div class="control-group <%= is_error?(@store, :name) %>">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :name, :class => 'input-xxlarge'  %><span class="help-inline"><%= @store.errors[:name].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :policy) %>">
        <%= f.label :policy, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :policy, :class => 'input-xxlarge' %><span class="help-inline"><%= @store.errors[:policy].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :owner_profession) %>">
        <%= f.label :owner_profession, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :owner_profession, :class => 'input-xxlarge' %><span class="help-inline"><%= @store.errors[:owner_profession].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :owner_trait) %>">
        <%= f.label :owner_trait, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :owner_trait, :class => 'input-xxlarge' %><span class="help-inline"><%= @store.errors[:owner_trait].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :bag_query) %>">
        <%= f.label :bag_query, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :bag_query, :class => 'input-xxlarge' %><span class="help-inline"><%= @store.errors[:bag_query].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :bag_total_value) %>">
        <%= f.label :bag_total_value, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :bag_total_value, :class => 'input-xxlarge' %>
            <span class="help-inline"><%= @store.errors[:bag_total_value].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :bag_min_value) %>">
        <%= f.label :bag_min_value, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :bag_min_value, :class => 'input-xxlarge' %>
            <span class="help-inline"><%= @store.errors[:bag_min_value].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :bag_max_value) %>">
        <%= f.label :bag_max_value, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :bag_max_value, :class => 'input-xxlarge' %>
            <span class="help-inline"><%= @store.errors[:bag_max_value].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@store, :tags) %>">
        <label class="control-label" for="store_tags">Tags</label>
        <div class="controls stream-box well well-small">
            <% @tags.each_with_index do |tag, index| %>
                <% previous = @tags[index-1] %>
                <% if (previous.cat != tag.cat) %>
                    <label><b><%= (tag.cat || "none").capitalize %></b></label>
                <% end %> 
                <label style="padding-left: 1rem">
                    <table>
                        <tr>
                            <td valign="top" style="padding-right: .5rem">
                                <%= check_box_tag "store[tag_ids][]", tag.id, @store.tags.include?(tag) %>
                            </td>
                            <td>
                                <%= tag.name %><br><small><%= tag.description %></small>
                            </td>
                        </tr>
                    </table>
                </label>
            <% end %>
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <label></label>
            <div id="result"></div>
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <label></label>
            <button type="submit" class="btn btn-primary">Save</button>
            <%= link_to 'Cancel', "/#{controller_name}", {:class => 'btn'} %>
            <button type="button" onclick="tryTheseValues()" class="btn btn-success">Try These Values</button>
        </div>
    </div>
<% end %>
<script>
function tryTheseValues() {
    var tags = document.querySelector("#store_bag_query").value;
    var totalValue = document.querySelector("#store_bag_total_value").value;
    var minValue = document.querySelector("#store_bag_min_value").value;
    var maxValue = document.querySelector("#store_bag_max_value").value;
    var checked = document.querySelectorAll("input[type=checkbox]");
    var clustering = "";
    for (var i=0; i < checked.length; i++) {
        var check = checked[i];
        var text = check.parentNode.nextElementSibling.textContent.trim();
        if (check.checked && text.indexOf("cluster:") > -1) {
            clustering = text.split("cluster:")[1];
        }
    }
    var opts = {fillBag: false};
    if (tags) { opts.tags = tags; }
    if (totalValue) { opts.totalValue = parseInt(totalValue,10); }
    if (minValue) { opts.minValue = parseInt(minValue,10); }
    if (maxValue) { opts.maxValue = parseInt(maxValue,10); }
    if (clustering && clustering !== "none") { opts.cluster = clustering; }
    console.log(opts);

    if (opts.cluster) {
        var output = "Stockpile: " + atomic.createStockpile(opts);
    } else {
        var output = "Bag: " + atomic.createBag(opts);
    } 
    document.getElementById('result').textContent = output;
}

</script>

app/views/stores/index.html.erb
<p align="left">
    <%= link_to 'New Store', new_store_path, {:class => 'btn btn-primary'} %>
    <%= link_to 'Export', '/export', {:class => 'btn btn-info'} %>
</p>
<% unless (@stores.empty?) %>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Owner</th>
                <th>Inventory</th>
                <th>Trade</th>
                <th>Tags</th>
                <th width="100"></th>
            </tr>
        </thead>
        <tbody>
            <% @stores.each do |store| %>
                <tr>
                    <td><%= link_to store.name, edit_store_path(store) %>
                        <% if (store.policy.present?) %>
                            <small><br><%= store.policy %></small>
                        <% end %>
                    </td>
                    <td><%= store.owner_profession %>
                        <% if (store.owner_trait.present?) %>
                            <small><br><%= store.owner_trait %></small>
                        <% end %>
                    </td>
                    <td><%= store.bag_query %></td>
                    <td><%= store.bag_total_value %></td>
                    <td>
                        <%= store.tags.pluck(:name).sort.map do |tag|
                            link_to tag, stores_path
                        end.join(', ').html_safe %> 
                    </td>
                    <td>
                        <%= link_to 'Clone', "/stores/clone/#{store.id}", :class => 'btn btn-mini btn-info' %>
                        <%= link_to 'Delete', store, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>No stores. </p>
<% end %>