config/routes.rb
Kibble::Application.routes.draw do

    match "/" => redirect("/items")
    
    resources :items
    resources :stores
    resources :tags
    resources :categories
    resources :rules
    resources :professions

    post 'items/update_tags' => "items#update_tags" 
    get 'items/clone/:id' => "items#clone" 
    get 'stores/clone/:id' => "stores#clone" 
    get 'professions/clone/:id' => "professions#clone" 
    get 'export' => "export#index"
    get 'validate' => "items#validate"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    attr_accessible :name, :cat, :description, :suppress_on_export, :rel

    belongs_to :category
    has_and_belongs_to_many :items
    has_and_belongs_to_many :professions
    has_and_belongs_to_many :stores
    has_and_belongs_to_many :seeds, :class_name => Profession, :join_table => 'professions_seeds'
    has_and_belongs_to_many :traits, :class_name => Profession, :join_table => 'professions_traits'

    scope :item_tags, where("rel like ?", "%|item|%").order(:cat, :name)
    scope :store_tags, where("rel like ?", "%|store|%").order(:cat, :name)
    scope :profession_tags, where("rel like ?", "%|profession|%").order(:cat, :name)
    scope :trait_tags, where("rel like ?", "%|trait|%").order(:cat, :name)
    scope :encounter_tags, where("rel like ?", "%|encounter|%").order(:cat, :name)
    
    def uses_count
        (items + professions + stores).size
    end
    
    validates :name, :cat, :presence => true
    validates :name, :uniqueness => true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    
    def index
        session[:tag_filter] = params[:filter] if params.has_key?(:filter)
        filter = session[:tag_filter]
        if (filter == 'professions')
            @tags = Tag.profession_tags + Tag.trait_tags
        elsif (filter == 'encounters')
            @tags = Tag.encounter_tags
        elsif (filter == 'stores')
            @tags = Tag.store_tags
        else
            @tags = Tag.item_tags
        end
    end

    def show
        @tags = Tag.find(params[:id])
        render "index"
    end

    def new
        @tag = Tag.new
    end

    def edit
        @tag = Tag.find(params[:id])
    end

    def create
        @tag = Tag.new(params[:tag])

        if @tag.save
            redirect_to tags_url, :notice => 'Tag was successfully created.'
        else
            render :action => "new"
        end
    end

    def update
        @tag = Tag.find(params[:id])

        if @tag.update_attributes(params[:tag])
            redirect_to tags_url, :notice => 'Tag was successfully updated.'
        else
            render :action => "edit"
        end
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        @tags = Tag.order(:cat, :name).all
        redirect_to tags_url, :notice => 'Tag was deleted.'
    end
    
end

app/views/tags/_form.html.erb
<%= render :partial => "shared/errors", :locals => { :model => @tag } %>
<%= form_for(@tag, :html => {:class => 'form-horizontal' }) do |f| %> 
    <div class="control-group <%= is_error?(@tag, :name) %>">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :name, :style => "font-weight: bold", :tabindex => 0 %><span class="help-inline"><%= @tag.errors[:name].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@tag, :cat) %>">
        <%= f.label :cat, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :cat %><span class="help-inline"><%= @tag.errors[:cat].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@tag, :rel) %>">
        <%= f.label :rel, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :rel %><span class="help-inline"><%= @tag.errors[:rel].join(", ") %></span>
            <span class="helptext">Pipe-delimited set of model names, e.g. "|item|profession|"</span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@tag, :description) %>">
        <%= f.label :description, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_area :description, :rows => 4 %><span class="help-inline"><%= @tag.errors[:description].join(", ") %></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
            <%= (@tag.items + @tag.professions + @tag.stores).map {|tag| tag.name}.join(", ") %>
        </div>
    </div>
    <%= render 'shared/keys' %>
<% end %>

app/views/tags/edit.html.erb
<%= render 'form' %>

app/views/tags/index.html.erb
<ul class="nav nav-tabs">
    <li <%= raw session[:tag_filter] == 'items' ? "class='active'" : "" %>>
        <%= link_to 'Items', tags_path(:filter => 'items') %>
    </li>
    <li <%= raw session[:tag_filter] == 'professions' ? "class='active'" : "" %>>
        <%= link_to 'Professions', tags_path(:filter => 'professions') %>
    </li>
    <li <%= raw session[:tag_filter] == 'stores' ? "class='active'" : "" %>>
        <%= link_to 'Stores', tags_path(:filter => 'stores') %>
    </li>
    <li <%= raw session[:tag_filter] == 'encounters' ? "class='active'" : "" %>>
        <%= link_to 'Encounters', tags_path(:filter => 'encounters') %>
    </li>
</ul>
<p><%= link_to 'New Tag', new_tag_path, {:class => 'btn btn-primary', :accesskey => 's'} %></p>
<% unless (@tags.empty?) %>
    <table class="table table-bordered table-hover">
        <colgroup>
            <col style="white-space: nowrap"/>
            <col/>
            <col/>
            <col style="width:50px"/>
        </colgroup>
        <thead>
            <tr>
                <th style="white-space: nowrap">Name</th>
                <th>Description</th>
                <th>Uses</th>
                <th width="50"></th>
            </tr>
        </thead>
        <tbody>
            <% @tags.each_with_index do |tag, index| %>
                <% if (index == 0 || @tags[index-1].cat != tag.cat) %>
                    <tr class="info">
                        <td colspan="4"><b><%= (tag.cat.present?) ? tag.cat.titleize : "-" %></b></td>
                    </tr>
                <% end %>
                <tr>
                    <td style="white-space:nowrap"><%= link_to tag.name, edit_tag_path(tag) %></td>
                    <td><%= tag.description %></td>
                    <td><%= tag.uses_count %></td>
                    <td>
                        <%= link_to 'Delete', tag, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>No tags, which is kinda amazing. </p>
<% end %>

<%= render 'shared/nav_keys' %>

app/views/tags/new.html.erb
<%= render 'form' %>