config/routes.rb
Kibble::Application.routes.draw do

    match "/" => redirect("/items")
    
    resources :items
    resources :stores
    resources :tags
    resources :categories
    resources :rules
    resources :professions

    post 'items/update_tags' => "items#update_tags" 
    get 'items/clone/:id' => "items#clone" 
    get 'stores/clone/:id' => "stores#clone" 
    get 'professions/clone/:id' => "professions#clone" 
    get 'export' => "export#index"
    get 'validate' => "items#validate"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/rule.rb
class Rule < ActiveRecord::Base
    attr_accessible :identifier, :parameters
    
    validates :identifier, :parameters, :presence => true
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
    
    def index
        @rules = Rule.order(:identifier, :parameters).all
    end

    def show
        @rule = Rule.find(params[:id])
        render "index"
    end

    def new
        @rule = Rule.new
    end

    def edit
        @rule = Rule.find(params[:id])
    end

    def create
        @rule = Rule.new(params[:rule])

        if @rule.save
            redirect_to rules_url, :notice => 'Rule was successfully created.'
        else
            render :action => "new"
        end
    end

    def update
        @rule = Rule.find(params[:id])

        if @rule.update_attributes(params[:rule])
            redirect_to rules_url, :notice => 'Rule was successfully updated.'
        else
            render :action => "edit"
        end
    end

    def destroy
        @rule = Rule.find(params[:id])
        @rule.destroy

        @rules = Rule.order(:identifier, :parameters).all
        redirect_to rules_url, :notice => 'Rule was deleted.'
    end
    
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= render :partial => "shared/errors", :locals => { :model => @rule } %>
<%= form_for(@rule, :html => {:class => 'form-horizontal' }) do |f| %> 
    <div class="control-group <%= is_error?(@rule, :identifier) %>">
        <%= f.label :identifier, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :identifier %><span class="help-inline"><%= @rule.errors[:identifier].join(", ") %></span>
        </div>
    </div>
    <div class="control-group <%= is_error?(@rule, :parameters) %>">
        <%= f.label :parameters, :class => 'control-label' %>
        <div class="controls">
            <%= f.text_field :parameters %><span class="help-inline"><%= @rule.errors[:parameters].join(", ") %></span>
        </div>
    </div>
    <%= render 'shared/keys' %>
<% end %>

app/views/rules/edit.html.erb
<%= render 'form' %>

app/views/rules/index.html.erb
<p><%= link_to 'New Rule', new_rule_path, {:class => 'btn btn-primary'} %></p>
<% unless (@rules.empty?) %>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Identifier</th>
                <th width="100%">Parameters</th>
                <th width="50"></th>
            </tr>
        </thead>
        <tbody>
            <% @rules.each_with_index do |rule, index| %>
                <tr>
                    <td><%= link_to rule.identifier, edit_rule_path(rule) %></td>
                    <td><%= rule.parameters %></td>
                    <td>
                        <%= link_to 'Delete', rule, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>No rules, no order! </p>
<% end %>

<p><b>category</b> = must have one of the tags in this category </p>
<p><b>linked</b> = if you have a tag in one group, you must a tag from the other group. You can only have one tag in each group.</p>

<%= render 'shared/nav_keys' %>

app/views/rules/new.html.erb
<%= render 'form' %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identifier:</b>
  <%= @rule.identifier %>
</p>

<p>
  <b>Parameters:</b>
  <%= @rule.parameters %>
</p>


<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>